~name: grabbing streams
~
~on:
~  schedule:
~    - cron: '0 */1 * * *'
~  
~  
~  workflow_dispatch:
~
~jobs:
~  build:
~    runs-on: ubuntu-latest
~
~    steps:
~      - uses: actions/checkout@v2
~
~       
~      - name: config
~        run: |
~          git config --global user.email "<>"
~          git config --global user.name "Update"
~      
~      
~      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/

      - name: grab m3u files (YouTube)
        run: |
            python3 youtube.py "https://www.youtube.com/watch?v=CEQVJ32aur8" > ../../streams/YouTube_Stream_1.m3u8
            python3 youtube.py "https://www.youtube.com/watch?v=CEQVJ32aur8" > ../../streams/YouTube_Stream_2.m3u8
      - name: git add
        run: |
          git add -A
~          ls -la 
~          
~      - name: commit & push
~        run: |
~          git commit -m "streams updated"
~          git push
